pipeline {
agent any
    stages {
        stage('Build1') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test1') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver1') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Complete1') {
            steps {
                echo 'Job Complete!'
            }
        }
    }
}
